# This workflow will check links on www.library.ucsf.edu.

name: Link check

on:
  schedule:
    # Run every day at 4:05 AM.
    - cron: '5 4 * * *'

  workflow_dispatch:

jobs:
  check:
  
    runs-on: ubuntu-latest

    steps:
    # Skip anything that is not *.ucsf.edu, and also skip Springshare (LibGuides, LibCal)
    # because it rate limits aggressively, and Zendesk because it uses Cloudflare to block bots
    # like this link-checker.
    - run: npx linkinator --concurrency 10 -r --skip '^(?!https?://.*.ucsf.edu/)|https?://calendars.library.ucsf.edu/|https?://guides.ucsf.edu/|https?://libraryhelp.ucsf.edu/' https://www.library.ucsf.edu/ -f csv
