# This workflow will check links on www.library.ucsf.edu.

name: Link check

on:
  schedule:
    # Run every day at 4:05 AM.
    - cron: '5 4 * * *'

  workflow_dispatch:

jobs:
  check:
  
    runs-on: ubuntu-latest

    steps:
    # Skip anything that is not *.library.ucsf.edu, and also skip calendars.library.ucsf.edu
    # because it rate limits aggressively.
    - run: npx linkinator --concurrency 10 -r --skip '^(?!https?://.*library.ucsf.edu/)|https://calendars.library.ucsf.edu/' https://www.library.ucsf.edu/ -f csv
