# This workflow will check that appointments are available for all consultants
# listed in LibCal. When there are no appointments available, it's usually
# because the user's Exchange connector needs to be re-authorized.

name: LibCal check

on:
  schedule:
    # Run every day at 4:05 AM.
    - cron: '5 4 * * *'

  workflow_dispatch:

defaults:
  run:
    working-directory: tools/check-consultation-calendars

jobs:
  check:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build --if-present
    - run: node index.js
