# This workflow will check links on www.library.ucsf.edu.

name: Link check

on:
  schedule:
    # Run every day at 4:05 AM.
    - cron: '5 4 * * *'

  workflow_dispatch:

jobs:
  check:
  
    runs-on: ubuntu-latest

    steps:
    - run: npx linkinator -r https://www.library.ucsf.edu/
